# Form implementation generated from reading ui file 'generator.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(153, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 150, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.minValue = QtWidgets.QLineEdit(self.centralwidget)
        self.minValue.setGeometry(QtCore.QRect(20, 90, 113, 21))
        self.minValue.setObjectName("minValue")
        self.maxValue = QtWidgets.QLineEdit(self.centralwidget)
        self.maxValue.setGeometry(QtCore.QRect(20, 120, 113, 21))
        self.maxValue.setObjectName("maxValue")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random Number Generator"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "50"))
        self.minValue.setText(_translate("MainWindow", "1"))
        self.minValue.setPlaceholderText(_translate("MainWindow", "min"))
        self.maxValue.setText(_translate("MainWindow", "100"))
        self.maxValue.setPlaceholderText(_translate("MainWindow", "max"))
