# Generated by Django 4.0 on 2021-12-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='comment',
        ),
    ]
